Add theme support
qmk/qmk_flasher pull request #43
Opened 2017-03-03 23:44 UTC by skullydazed

2017-03-07 03:03 UTC, ItsHarper requested changes
See gitter for more information on weird malformed JSON bug.

2017-03-07 03:03 UTC, ItsHarper commented on src/MainWindow/app.js
> +let currentTheme = $('#theme-dropdown');
It's nitpicky for sure*, but for clarity and consistency this would probably be better named currentThemeDropdown.

\* I can be a big perfectionist sometimes. Let me know if you think I should overlook small stuff like this.

2017-03-07 03:03 UTC, ItsHarper commented on src/main.js
> +    theme: 'default'
As it turns out, this will only set the default if the settings have never been set before, even if not all of the options are set.

So, when I tried to run the app, it crashed, because the settings file existed but didn't contain the theme option. 

It's a non-issue for now, because we haven't shipped code that uses settings yet, but for the future, we need to track [this issue](https://github.com/nathanbuchar/electron-settings/issues/53). If it doesn't get resolved, we'll need to manually check for the existence of any setting we add after shipping. Though I would prefer one of us make a PR to fix that, rather than complicating our code.

2017-03-07 03:03 UTC, ItsHarper commented on src/MainWindow/themes/platform.css
> +}
The text size on the choose hex button is still off in Windows for this theme.

2017-03-07 03:03 UTC, ItsHarper commented on src/MainWindow/themes/nantucket-selectric.css
> +#gear-menu > span {
The gear looks grayed out in this theme (until you hover over it, on Windows anyway)

2017-03-07 03:03 UTC, ItsHarper commented on src/MainWindow/themes/modern-selectric.css
> +.dropdown-menu {
The options in the theme selection dropdown look grayed out (on Windows at least).

2017-03-12 16:48 UTC, skullydazed commented on src/main.js
> +    theme: 'default'
Per our conversation on gitter, `settings.applyDefaultsSync();` fixes this.

2017-03-12 16:51 UTC, skullydazed commented on src/MainWindow/themes/modern-selectric.css
> +.dropdown-menu {
Can you give me a screenshot? On mac they look normal.

2017-03-12 16:57 UTC, skullydazed commented on src/MainWindow/themes/nantucket-selectric.css
> +#gear-menu > span {
Latest commit should fix this.

2017-03-12 16:57 UTC, skullydazed commented on src/MainWindow/themes/modern-selectric.css
> +.dropdown-menu {
I also added color/background-color to these. Hopefully it helps.

2017-03-12 16:59 UTC, skullydazed commented on src/MainWindow/themes/platform.css
> +}
Do you have a size you think would work?

2017-03-14 04:11 UTC, NoahAndrews commented on src/MainWindow/themes/modern-selectric.css
> +.dropdown-menu {
After pulling your latest changes: ![image](https://cloud.githubusercontent.com/assets/10224994/23885617/c071c374-084a-11e7-9fbb-170b56c53f7f.png)

2017-03-14 04:16 UTC, NoahAndrews commented on src/MainWindow/app.js
> +  $status.scrollTop(statusBox.scrollHeight);
You missed a statusBox when renaming.

2017-03-14 04:30 UTC, NoahAndrews commented on src/MainWindow/themes/platform.css
> +}
I'd say 12 or 13 pixels.

12px: 
![image](https://cloud.githubusercontent.com/assets/10224994/23885869/b70961be-084c-11e7-87f5-650551626fd0.png)

13px: 
![image](https://cloud.githubusercontent.com/assets/10224994/23885893/e82361b4-084c-11e7-90f7-fcafa3abb1d6.png)


14px: 
![image](https://cloud.githubusercontent.com/assets/10224994/23885875/c38a0024-084c-11e7-83bc-c0b7b745604a.png)

2017-03-14 04:40 UTC, NoahAndrews commented
I have no idea why it's doing this, since I don't think you touched that file, but this branch also messed up the menu:
![image](https://cloud.githubusercontent.com/assets/10224994/23886134/c4f9846e-084e-11e7-9445-cd4e7a0fead3.png)

Sorry for not including that in my original report. I've confirmed this looks fine in master.

2017-03-16 19:31 UTC, skullydazed commented on src/MainWindow/themes/modern-selectric.css
> +.dropdown-menu {
OK, I think I've got this fixed.

2017-03-16 19:31 UTC, skullydazed commented on src/MainWindow/app.js
> +  $status.scrollTop(statusBox.scrollHeight);
Thanks! Fixed it.

2017-03-16 19:32 UTC, skullydazed commented
Not sure why you're seeing the greyed out menu. I may have to dig up my windows laptop this weekend to do some testing.

2017-04-05 15:26 UTC, merged